import 'package:flutter/material.dart';

const Color millennialPink = Color(0xffffd1dc);

final List<Color> colors = [
  Colors.red,
  Colors.red[100],
  Colors.red[200],
  Colors.red[300],
  Colors.red[400],
  Colors.redAccent,
  Colors.orange,
  Colors.orange[100],
  Colors.orange[200],
  Colors.orange[300],
  Colors.orange[400],
  Colors.orangeAccent,
  Colors.yellow,
  Colors.yellow[100],
  Colors.yellow[200],
  Colors.yellow[300],
  Colors.yellow[400],
  Colors.yellowAccent,
  Colors.green,
  Colors.green[100],
  Colors.green[200],
  Colors.green[300],
  Colors.green[400],
  Colors.greenAccent,
  Colors.blueAccent,
  Colors.indigo,
  Colors.indigo[100],
  Colors.indigo[200],
  Colors.indigo[300],
  Colors.indigo[400],
  Colors.indigoAccent,
  Colors.teal,
  Colors.teal[100],
  Colors.teal[200],
  Colors.teal[300],
  Colors.teal[400],
  Colors.tealAccent,
];